---
# tasks file for remove-pi-user
- name: "Ensure user 'pi' is removed"
  become: yes
  user:
    name: "pi"
    state: absent


- name: "Ensure group 'pi' is removed"
  become: yes
  group:
    name: "pi"
    state: absent
