---
- name: "Enable Proxy"
  block:
  - name: "Lockup if {{ item }} config File exists"
    stat: 
      path: "{{ system.docker.store }}/Docker Swag/config/nginx/proxy-confs/{{ item }}.subfolder.conf"
    register: config_file_stat

  - name: "Copy {{ item }} file if not exists"
    copy:
      src: "{{ system.docker.store }}/Docker Swag/config/nginx/proxy-confs/{{ item }}.subfolder.conf.sample"
      dest: "{{ system.docker.store }}/Docker Swag/config/nginx/proxy-confs/{{ item }}.subfolder.conf"
      remote_src: yes
    when: 
      - not config_file_stat.stat.exists

  when: 
    - item in role_names
