---
# tasks file for fileserver
- name: Make Sure Fileserver Dirs exists
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ system.docker.store }}/Fileserver/files"
    - "{{ system.docker.store }}/Fileserver/config"

- name: "Copy Config"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "default.conf" , dest: "{{ system.docker.store }}/Fileserver/config/default.conf"}

- name: "Start Container for 'Fileserver'"
  community.docker.docker_container:
    container_default_behavior: compatibility
    env:
      TZ: "{{ system.docker.timezone }}"
    name: "Fileserver"
    network_mode: default
    networks:
      - name: external_network
        aliases:
          - "fileserver"
    image: "nginx"
    state: "started"
    pull: yes
    ports:
      - "8086:8080"
    recreate: yes
    restart_policy: "unless-stopped"
    volumes:
      - "{{ system.docker.store }}/Fileserver/files:/data/fileserver/"
      - "{{ system.docker.store }}/MeTube/downloads:/data/fileserver/MeTube"
      - "{{ system.docker.store }}/Fileserver/config/default.conf:/etc/nginx/conf.d/default.conf:ro"

- name: "Wait for Fileserver to be Up @ 'http://{{ hostvars[inventory_hostname].ansible_host }}:8086' fo 60 Secconds"
  command: "curl --silent -I http://{{ hostvars[inventory_hostname].ansible_host }}:8086"
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: 60
  delay: 1
  changed_when: false
