---
# tasks file for docker
- name: Set sysctl File Limits
  become: yes
  copy:
    src: 50-fs.conf
    dest: /etc/sysctl.d

- name: Set Shell File Limits
  become: yes
  copy:
    src: 91-nofiles.conf
    dest: /etc/security/limits.d

- name: Reboot machine
  become: yes
  reboot:
    msg: "Reboot initiated by Ansible for kernel"
    # TODO: Only if Limits changed

- name: Check is docker installed
  shell: command -v docker
  register: is_docker_installed
  ignore_errors: yes
  changed_when: is_docker_installed.rc != 0

- name: Download Docker install Script if needed
  get_url:
    url: https://get.docker.com
    dest: /tmp/install-docker.sh
    mode: '0770'
  when: is_docker_installed.rc != 0

- name: Install Docker if needed
  become: yes
  shell: ./install-docker.sh
  args:
    chdir: /tmp/
  when: is_docker_installed.rc != 0

- name: "Make sure Docker Apt Packages are installed"
  become: yes
  apt: 
    name: 
      - docker
      - docker-compose
    state: present

- name: "Make sure latest Pip Version is installed"
  become: yes
  shell: pip3 install --upgrade pip
  args:
    chdir: /tmp/

- name: "Make sure Docker Pip Packages are installed"
  become: yes
  pip:
    name: 
      - docker
      - docker-compose
    state: latest

- name: "Make shure old Docker Pip Packages are not installed"
  become: yes
  pip:
    name: 
      - docker-py
    state: absent

- name: Make Sure Docker Data-Dir exists
  become: yes
  file:
    path: "{{ system.docker.store }}"
    state: directory
    mode: 0777
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    recurse: yes

- name: Make Sure Docker Network exists
  community.general.docker_network:
    name: "{{ item }}"
  with_items:
    - internal_network
    - external_network
